quiz_start: "Вопросов: {number}"

long_question: "{question}\n\n1. {option_0}\n\n2. {option_1}\n\n3. {option_2}"
right_answer: "{question}\n\n*Верно - {answer}*"
wrong_answer: "{question}\n\n*Неверно! Правильный ответ - {answer}*"

quiz_finish: |
  *Вопросы кончились*
  ✅Правильные ответы - *{right_count}*
  🚫Неправильные ответы - *{wrong_count}*
  Начать заново - */start*

false_start: "*Последний вопрос активен*, либо же /cancel чтобы закончить"
false_cancel: "Тест не начат"

help: |
  Тест в Quizlet(без вопросов с картинками): https://quizlet.com/_ag5fxz?x=1jqt&i=2e14wv\n\n
  Вопросы-ответы в таблице: https://docs.google.com/spreadsheets/d/1P-c0Q903g3sNPo0X7bjDxXp_zUIB-hUd

  Гугл диск с контентом: https://drive.google.com/drive/folders/1dXrh7nTbH9JRyONfaAeTzrripG3G3TgQ?usp=sharing
  Особое внимание к папке Экзы : https://drive.google.com/drive/folders/1od60pDY_z4dHlkzPWfBdpx7y8wOyd4hs?usp=sharing

  Ошибки или баги - пишите @searayeah
